### ISSUE TITLE
Pathfinding fails

### ISSUE THREAD

**Issue by marclafr** [marclafr/Digital-Wolves-Games#12]
Status: New.
Title: Pathfinding fails
Category: Loop Units (JPS find path)
Detailed Descriprion: If you block the way with buildings (i.e. walls) although it has a small space to pass, units won't find it.
Steps to reproduce: Build walls all along a line as close as you can of the first zone of the map.
Priority: P1.
Severity: S1.

**Comment by Yulna** [comment]
In my case it even fails on an open field
